name: Validate HTML in Jekyll output

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      uses: helaili/jekyll-action@v2
      with:
        build_only: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.0.0
      with:
        root: .
