name: Validate HTML in Jekyll output

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Jekyll site for testing

    steps:
    - uses: actions/checkout@v2

    - name: Build the site in the Jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        
    - name: List result of Jekyll build
      run: ls _site/ -l

    - name: Publish builds
      uses: actions/upload-artifact@v2
      with:
        name: Built site ${{ github.run_number }}
        path: ./_site

  validate:

    runs-on: ubuntu-latest
    name: Validate HTML
    needs: [build]

    steps:
    - name: Fetch built site
      uses: actions/download-artifact@v2
      with:
        name: Built site ${{ github.run_number }}
        path: ./_site

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.0.0
      with:
        root: _site/

  check-links:

    runs-on: ubuntu-latest
    name: Check links
    needs: [build]

    steps:
    - name: Fetch built site
      uses: actions/download-artifact@v2
      with:
        name: Built site ${{ github.run_number }}
        path: ./_site

    - name: Check links
      run: |
        pip install pytest-check-links
        pytest _site/ --check-links
